version: "3"
services:
  hades:
    build:
      context: hades
      dockerfile: .docker/Dockerfile
    ports:
      - "8081:80"
    environment:
      - JWT_KEY
      - DB_DSN=${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(hades-db)/${HADES_DB_NAME}
    depends_on:
      - "hades-db"
    restart: on-failure
  hades-db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=${HADES_DB_NAME}
      - MYSQL_USER
      - MYSQL_PASSWORD
  zeus:
    build:
      context: zeus
      dockerfile: .docker/Dockerfile
    ports:
      - "8082:80"
  aphrodite:
    build:
      context: aphrodite
      dockerfile: .docker/Dockerfile
    ports:
      - "8083:80"
  apollo:
    build:
      context: apollo
      dockerfile: .docker/Dockerfile
    ports:
      - "8084:80"
